### PR TITLE
Fix broken build on Go 1.23

### LINKED ISSUE #356: Fails to build on Go 1.23
```
# github.com/grafana/pyroscope-go/godeltaprof/internal/pprof
vendor/github.com/grafana/pyroscope-go/godeltaprof/internal/pprof/delta_mutex.go:30:20: undefined: runtime_cyclesPerSecond
vendor/github.com/grafana/pyroscope-go/godeltaprof/internal/pprof/proto.go:320:8: undefined: runtime_expandFinalInlineFrame
``` 

The service fails to build due to dependency issue on Go 1.23. The fix is solved upstream on newer releases.

### PR DESCRIPTION
**Pull request by errnoh**
`github.com/grafana/pyroscope-go/godeltaprof` dependency prevents `coroot` from building with Go 1.23. This is solved by bumping the version to more recent one. ( https://github.com/grafana/pyroscope-go/issues/117 )

fixes #356

### CODE REVIEW

**Comment by errnoh** [comment]
Added changes from `go mod tidy` to the commit.

**Review by apetruhin — APPROVED** [review]

**Comment by apetruhin** [comment]
@errnoh, thank you!
