### ISSUE TITLE
Fails to build on Go 1.23

### ISSUE THREAD

**Issue by errnoh** [coroot/coroot#356]
```
# github.com/grafana/pyroscope-go/godeltaprof/internal/pprof
vendor/github.com/grafana/pyroscope-go/godeltaprof/internal/pprof/delta_mutex.go:30:20: undefined: runtime_cyclesPerSecond
vendor/github.com/grafana/pyroscope-go/godeltaprof/internal/pprof/proto.go:320:8: undefined: runtime_expandFinalInlineFrame
``` 

The service fails to build due to dependency issue on Go 1.23. The fix is solved upstream on newer releases.
